Make CRS setup part of the ledger abstraction
EspressoSystems/reef pull request #29
Opened 2022-03-24 21:08 UTC by jbearer

Closes #28

2022-03-24 21:17 UTC, tri-joe requested changes
The type of `crs()` probably shouldn't require cloning it (since it's potentially quite large)

2022-03-24 21:17 UTC, tri-joe commented on src/cap.rs
> +    fn crs() -> UniversalParam {
Why return `UniversalParam` rather than something like `&'static UniversalParam` or `Arc<UniversalParam>`?

2022-03-24 21:21 UTC, jbearer commented on src/cap.rs
> +    fn crs() -> UniversalParam {
Good point. What about `<'a> Cow<'a, UniversalParam>`, which is I think the most compatible with the proving key setup APIs.

2022-03-24 21:23 UTC, jbearer commented on src/cap.rs
> +    fn crs() -> UniversalParam {
Actually you know what I think `Arc` would be fine and simpler, I'll try that

2022-03-24 23:10 UTC, jbearer commented on src/cap.rs
> +    fn crs() -> UniversalParam {
Nope, turns out `&'static` is the only one that really works with the rest of the codebase

2022-03-24 23:25 UTC, alxiong commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
I think the downstream have to use `test_apis` feature flag to use Aztec SRS indicates a problem in our API design. 

@zhenfeizhang I think we should make [this](https://github.com/EspressoSystems/cap/blob/a9489cff402408953bae25d4b27b5cdaa481f9dd/src/proof/mod.rs#L115) and [this](https://github.com/EspressoSystems/cap/blob/a9489cff402408953bae25d4b27b5cdaa481f9dd/src/proof/mod.rs#L123) `pub` and remove [this](https://github.com/EspressoSystems/cap/blob/1f4daf7368bdcbea501a96cdfb1219e5019f12c6/src/testing_apis.rs#L53). So that `reef` doesn't depend on test-apis feature flag.

2022-03-24 23:25 UTC, alxiong commented on src/traits.rs
> +    fn crs() -> &'static UniversalParam;
let's use srs instead for consistency.

2022-03-25 00:03 UTC, alxiong commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
hmm... actually giving another thought, @jbearer let's use [this api ](https://github.com/EspressoSystems/cap/blob/main/src/proof/mod.rs#L77) instead and avoid the `test_apis` flag.

2022-03-25 00:40 UTC, jbearer commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
But then `reef` will only support BN254 curve? Is that okay? cc @tri-joe

2022-03-25 00:59 UTC, alxiong commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
in case we want to make the changes: https://github.com/EspressoSystems/cap/pull/30

2022-03-25 16:52 UTC, jbearer commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
Well the `cap` module of reef is a mock implementation that's only intended to be used for testing anyways. It's up to the actual products (CAPE and Espresso) to construct their production SRS in a secure way (which is why it's important to make `srs()` a trait function. Probably what I should actually do is guard the `cap` module with a `testing` feature flag.

2022-03-25 17:25 UTC, zhenfeizhang commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
Ah... that makes sense to me. (did not realize that reef is for testing only)

2022-03-25 18:34 UTC, jbearer commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
The trait definitions are for production but `cap` is just a simple test implementation of the traits so we can write tests for the traits

2022-03-25 22:44 UTC, alxiong approved these changes

2022-03-26 00:15 UTC, tri-joe approved these changes
LGTM

2022-03-26 00:19 UTC, merged

2022-03-26 00:20 UTC, tri-joe commented on Cargo.toml
> +jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
cc @fkrell re: our discussion of BN254 vs BLS curves, especially https://github.com/EspressoSystems/espresso/issues/95 -- in short, the wallet code is now specifically using BN254 because of the existing SRS